version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports: 
      - "8080:8080"
    volumes: 
      - "$PWD/Jenkins/JenkinsVolume:/var/jenkins_home"
    networks: 
      - net
  debian:
    container_name: ssh_debian
    image: ssh_debian_image
    build:
      context: BaseDebian  
    networks: 
      - net
networks:
  net:
