version: '3'
services:
  mysql:
    container_name: mysqldemoapp
    image: mysqlimage
    build:
      context: .
    ports: 
      - "3306:3306"
networks: 
  default: 
    external: 
      name: net
