version: '3'
services:
  covidportal:
    container_name: covidportal
    image: covidportal:springboot
    build:
      context: .  
    ports: 
      - "8080:8080"
networks: 
  default: 
    external: 
      name: net
